# This is a basic workflow to help you get started with Actions

name: Pipeline-QA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "The-great-pipeline-of-pipelines" ]
  pull_request:
    branches: [ "The-great-pipeline-of-pipelines" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    call-jmeter:
      uses: ./.github/workflows/Performance_Test_Workflow.yml
      secrets:
        jmeter_username: ${{ secrets.SOAP_USERNAME }}
        jmeter_password: ${{ secrets.SOAP_PASSWORD }}
        mail_username: ${{ secrets.MAIL_USERNAME }}
        mail_password: ${{ secrets.MAIL_PASSWORD }}