# This is a basic workflow to help you get started with Actions

name: CI-Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    call-performancetest:
      uses: ./.github/workflows/Performance_Test_Workflow.yml
      secrets: inherit
        
    call-apitest:
      needs: call-performancetest
      if: always()
      uses: ./.github/workflows/soaptest.yml
      secrets: inherit
    
    call-unittest:
      needs: call-apitest
      if: always()
      uses: ./.github/workflows/dotnet.yml
      secrets: inherit

    call-guitest:
      needs: call-unittest
      if: always()
      uses: ./.github/workflows/playwright.yml
      secrets: inherit