name: Playwright Tests
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Saucectl RUN
      uses: saucelabs/saucectl-run-action@v3
      with:
        concurrency: 10

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright test Chromium
      run: npx playwright test --project chromium

    - name: Run Playwright test Firefox
      run: npx playwright test --project firefox

    - name: Run Playwright test Webkit
      run: npx playwright test --project webkit

    - name: Run Saucelabs test
      run: saucectl run --region eu-central-1

    - name: Saucectl RUN - Config Driven
      uses: saucelabs/saucectl-run-action@v3
      with:
        working-directory: ./examples/cucumber/

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./gui-gui-testing/playwright-report/
        retention-days: 30
