name: SoapUI Tests

on:
  workflow_call:

jobs:
  soapui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Run SoapUI Tests
        run: |
          docker run -i --rm \
          -v .:/opt/soapui/projects \
          -v tests:/opt/soapui/projects/testresult \
          lukastosic/docker-soapui \
          -s "Log in testing" \
          -r -j \
          -f /opt/soapui/projects/testresult \
          -I "/opt/soapui/projects/Soap-try-soapui-project.xml" > tests/testOutput.txt

      - name: Test results
        run: |
          cat tests/testOutput.txt

      - name: verify there are no test failures
        run: |
          if grep -q "(0 failed)" tests/testOutput.txt
          then echo "Success: No test failures" 
          else
          echo "Error: there are test failures, check tests/testOutput.txt for more information"
          exit 1 
          fi
          
      # Upload SoapUI logs as an artifact
      - name: Upload SoapUI Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.TIMESTAMP}}_soapUi-test-logs
          path: tests/testOutput.txt
