name: Performance Test pipeline

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the "Gab-pipeline-test-branche" branch
  push:
    branches: [ "Gab-pipeline-test-branche" ]

  pull_request:

jobs:
  # This workflow contains a single job called "performance-test-build"
  performance-test-build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    # Setup Java for JMeter
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    # Setup .NET if needed
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: '6.0'
    
    # Installing Jmeter to run tests
    - name: Install JMeter
      run: |
        wget -v https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xzf apache-jmeter-5.6.2.tgz
        echo "${PWD}/apache-jmeter-5.6.2/bin" >> $GITHUB_PATH

    # Run JMeter Test
    - name: Run JMeter Test
      run: |
        jmeter -n -t "/git/Gab-pipeline-test-branche/sourceCode/.github/JMeterTestPlan/Demo web shop Tricentis.jmx" -l testresults.jtl -e -o "/git/Gab-pipeline-test-branche/sourceCode/.github/JMeterTestPlan/Results/" -j jmeter.log
