name: Performance Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "Gab-pipeline-test-branche" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "performance-test-build"
  performance-test-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Java for JMeter
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    # Setup .NET if needed
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: '6.0'

    # Run JMeter Test
    - name: Run JMeter Test
      run: |
        jmeter -n -t path/to/your/testplan.jmx -l testresults.jtl -e -o path/to/output/folder
